"""empty message

Revision ID: 49adf4a20588
Revises: 8f1e64d59481
Create Date: 2022-10-01 21:36:26.654503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49adf4a20588'
down_revision = '8f1e64d59481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'time')
    # ### end Alembic commands ###
