"""empty message

Revision ID: 8f1e64d59481
Revises: 
Create Date: 2022-09-29 21:15:01.807154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1e64d59481'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_url', sa.Text(), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_page_url'), 'video', ['page_url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_page_url'), table_name='video')
    op.drop_table('video')
    # ### end Alembic commands ###
