"""empty message

Revision ID: 9d3334f65d77
Revises: 49adf4a20588
Create Date: 2022-10-02 21:30:05.638744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3334f65d77'
down_revision = '49adf4a20588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'page_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('video', 'video_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'video_url',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('video', 'page_url',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
