"""empty message

Revision ID: f2363b28258c
Revises: 49adf4a20588
Create Date: 2022-10-06 19:46:48.902758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2363b28258c'
down_revision = '49adf4a20588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('last_played', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'last_played')
    # ### end Alembic commands ###
